A=6
B=3
C=9
result = A*B
print ('result = ',result)
result =A+B+C*B+C+A*B
print ('result =',result)
result = A+B
print ('result =',result)
result =A*B+C+A*B+C+A*B+C
print ('result =',result)
result = A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A*B
print ("result =",result)
result = A+C
print ('result =',result)
result = A+B
print ('result =',result)
result = A+C
print ('result =',result)
